name: Build macOS Package

on:
  push:
    branches: [dev4]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Runner Architecture # <--- ДОБАВЬТЕ ЭТОТ ШАГ
        run: uname -m

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'clang_64'

      - name: Configure and Build
        run: |
        rm -rf build
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64"
        cmake --build build --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: build/ImagoRef_v*_macOS.pkg # Немного поправил маску для поиска файла
