name: Build Windows Installer

on:
  push:
    branches: [ dev4 ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
          setup-python: false

      - name: Setup NSIS
        uses: crazy-max/ghaction-nsis@v3

      - name: Configure CMake
        run: cmake -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release

      - name: Build and Package
        run: cmake --build build --config Release --target PACKAGE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: build/ImagoRef-*-win64.exe
